### Challenge 1

The challenge is to write code to add tasks to the queue.

Hints:

- checkout branch challenge-1
- Look in celery_app.demo.py for the TODO section relating to challenge 1
- Look in celery_app.app.tasks to identify the function names and expected parameters of the the celery task
- In celery_app.demo.py write a loop that will iterate 2500 times.  Inside the loop, use the two helper functions get_random_x and get_random_y to get suitable x and y values, add these values to the queue.  You will need to use the special celery delay function.
- Rebuild the docker containers after you have made your changes, then run demo.py within the docker container using docker exec
- You should now see you tasks being added to the queue in flower, and hopefully being successfully processed.  You can optionally confirm that things are working by looking in qgis or pgadmin to see the items being added to the database table

Troubleshooting:

- Use docker logs docker logs celeryworkshopgeopython2018_celery_1 to view console and view python errors
- Use Flower to view failed task details.  You may be able to debug from the python output there
- If you are reall stuck, the solution is on the master branch

# Challenge 2

The challenge is to get celery to retry processing a task in the event of a recoverable error.

Hints:

- checkout branch challenge-2
- rebuild the docker containers, then run demo.py.  Observe that some tasks fail and none are retried
- Check the celery docs for retrying.  http://docs.celeryproject.org/en/latest/userguide/tasks.html#retrying
- Look in celery_app.app.service to see where a random artificial error is thrown.  Note the error type.
- In the place where the celery task is executed (look for TODO - challenge 2), handle the above error using python exception handling, and trigger the celery retry mechanism.  See if you can also add a retry delay.
- Rebuild the docker containers after you have made your changes, then run demo.py within the docker container using docker exec
- If you have been successfull, you should see the retry counter in flower incrementing, and most likely no fails.  All tasks should pass after being retried.
